version: "3"

services:
  max1:
    image: quay.io/codait/max-toxic-comment-classifier
    restart: always
  max2:
    image: quay.io/codait/max-toxic-comment-classifier
    restart: always
  max3:
    image: quay.io/codait/max-toxic-comment-classifier
    restart: always
  max4:
    image: quay.io/codait/max-toxic-comment-classifier
    restart: always

  scaler:
    build: .
    environment:
      token: change_this_to_your_token
    ports:
      - 7777:5000
    links:
      - max1
      - max2
      - max3
      - max4